export const QUERY_GET_BOOKING_BY_TOUR_ID = 'QUERY_GET_BOOKING_BY_TOUR_ID'
export const QUERY_AGENT_IN_OPERATOR = 'QUERY_AGENT_IN_OPERATOR'
export const QUERY_GET_BOOKING_PAX_BY_BOOKING_ID =
  'QUERY_GET_BOOKING_PAX_BY_BOOKING_ID'

export const QUERY_GET_TOUR_SERVICE_BY_TOUR_ID =
  'QUERY_GET_TOUR_SERVICE_BY_TOUR_ID'

export const QUERY_GET_SUPPLIER = 'QUERY_GET_SUPPLIER'
export const QUERY_GET_BOOKINGS_TOUR_ID = 'QUERY_GET_BOOKINGS_TOUR_ID'
export const QUERY_GET_BOOKING_BY_ID = 'QUERY_GET_BOOKING_BY_ID'
export const QUERY_GET_TOUR_BY_ID = 'QUERY_GET_TOUR_BY_ID'
export const QUERY_SEARCH_CLIENT = 'QUERY_SEARCH_CLIENT'
export const QUERY_UPDATE_BOOKING = 'QUERY_UPDATE_BOOKING'

export const QUERY_GET_CLIENT = 'QUERY_GET_CLIENT'
