import HeaderClient from '@/components/header'
import React from 'react'
import StoreProvider from '../store/provider'
import DispatchAsync from '@/context/DispatchAsync'
import './globals.css'

export const metadata = {
  title: 'Tour Dasboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="flex-col md:flex">
            <HeaderClient />

            <div className="mt-[5rem] mx-10">
              <DispatchAsync>{children}</DispatchAsync>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  )
}
